// <auto-generated />
namespace PortfolioSite.DataContexts.WebStoreMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddRecordId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRecordId));
        
        string IMigrationMetadata.Id
        {
            get { return "201507141019457_AddRecordId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
